version: "3"
services:
  master:
    build: 
      context: .
      dockerfile: ./services/master/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    ports:
      - "3000:3000"
  spawner:
    build: 
      context: .
      dockerfile: ./services/spawner/Dockerfile
    deploy:
      restart_policy:
        condition: on-failure
    depends_on:
      - master
    environment:
      - "HOTEL_MASTER_ADDRESS=master:3001"
