version: '3'
services:
  master:
    build: 
      context: .
      dockerfile: ./services/master/Dockerfile
  spawner:
    build: 
      context: .
      dockerfile: ./services/spawner/Dockerfile
