// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/common.proto

package hotel_pb

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type SpawnerStatus struct {
	// The game ID that this spawner supports.
	// TODO: This could eventually be a list of multiple supported IDs.
	// Required.
	SupportedGameId string `protobuf:"bytes,1,opt,name=supported_game_id,json=supportedGameId,proto3" json:"supported_game_id,omitempty"`
	// The number of running servers managed by this spawner.
	// Required.
	NumGameServers uint32 `protobuf:"varint,2,opt,name=num_game_servers,json=numGameServers,proto3" json:"num_game_servers,omitempty"`
	// The maximum number of servers this spawner can support.
	// Required.
	MaxGameServers       uint32   `protobuf:"varint,3,opt,name=max_game_servers,json=maxGameServers,proto3" json:"max_game_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnerStatus) Reset()         { *m = SpawnerStatus{} }
func (m *SpawnerStatus) String() string { return proto.CompactTextString(m) }
func (*SpawnerStatus) ProtoMessage()    {}
func (*SpawnerStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_1747d3070a2311a0, []int{0}
}

func (m *SpawnerStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnerStatus.Unmarshal(m, b)
}
func (m *SpawnerStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnerStatus.Marshal(b, m, deterministic)
}
func (m *SpawnerStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnerStatus.Merge(m, src)
}
func (m *SpawnerStatus) XXX_Size() int {
	return xxx_messageInfo_SpawnerStatus.Size(m)
}
func (m *SpawnerStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnerStatus.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnerStatus proto.InternalMessageInfo

func (m *SpawnerStatus) GetSupportedGameId() string {
	if m != nil {
		return m.SupportedGameId
	}
	return ""
}

func (m *SpawnerStatus) GetNumGameServers() uint32 {
	if m != nil {
		return m.NumGameServers
	}
	return 0
}

func (m *SpawnerStatus) GetMaxGameServers() uint32 {
	if m != nil {
		return m.MaxGameServers
	}
	return 0
}

func init() {
	proto.RegisterType((*SpawnerStatus)(nil), "hotel_pb.SpawnerStatus")
}

func init() { proto.RegisterFile("proto/common.proto", fileDescriptor_1747d3070a2311a0) }

var fileDescriptor_1747d3070a2311a0 = []byte{
	// 158 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2a, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3, 0x03, 0x73, 0x84, 0x38, 0x32, 0xf2, 0x4b,
	0x52, 0x73, 0xe2, 0x0b, 0x92, 0x94, 0xfa, 0x19, 0xb9, 0x78, 0x83, 0x0b, 0x12, 0xcb, 0xf3, 0x52,
	0x8b, 0x82, 0x4b, 0x12, 0x4b, 0x4a, 0x8b, 0x85, 0xb4, 0xb8, 0x04, 0x8b, 0x4b, 0x0b, 0x0a, 0xf2,
	0x8b, 0x4a, 0x52, 0x53, 0xe2, 0xd3, 0x13, 0x73, 0x53, 0xe3, 0x33, 0x53, 0x24, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xf8, 0xe1, 0x12, 0xee, 0x89, 0xb9, 0xa9, 0x9e, 0x29, 0x42, 0x1a, 0x5c, 0x02,
	0x79, 0xa5, 0xb9, 0x10, 0x55, 0xc5, 0xa9, 0x45, 0x65, 0xa9, 0x45, 0xc5, 0x12, 0x4c, 0x0a, 0x8c,
	0x1a, 0xbc, 0x41, 0x7c, 0x79, 0xa5, 0xb9, 0x20, 0x45, 0xc1, 0x10, 0x51, 0x90, 0xca, 0xdc, 0xc4,
	0x0a, 0x54, 0x95, 0xcc, 0x10, 0x95, 0xb9, 0x89, 0x15, 0x48, 0x2a, 0x93, 0xd8, 0xc0, 0x4e, 0x34,
	0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x93, 0x62, 0xe0, 0xc0, 0xb8, 0x00, 0x00, 0x00,
}
