// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/spawner-service.proto

package hotel_pb

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CheckStatusRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStatusRequest) Reset()         { *m = CheckStatusRequest{} }
func (m *CheckStatusRequest) String() string { return proto.CompactTextString(m) }
func (*CheckStatusRequest) ProtoMessage()    {}
func (*CheckStatusRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028c64f744b4b475, []int{0}
}

func (m *CheckStatusRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStatusRequest.Unmarshal(m, b)
}
func (m *CheckStatusRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStatusRequest.Marshal(b, m, deterministic)
}
func (m *CheckStatusRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStatusRequest.Merge(m, src)
}
func (m *CheckStatusRequest) XXX_Size() int {
	return xxx_messageInfo_CheckStatusRequest.Size(m)
}
func (m *CheckStatusRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStatusRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStatusRequest proto.InternalMessageInfo

type CheckStatusResponse struct {
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=hotel_pb.Status" json:"status,omitempty"`
	// The number of currently running game servers managed by the spawner.
	RunningGameServers uint32 `protobuf:"varint,2,opt,name=running_game_servers,json=runningGameServers,proto3" json:"running_game_servers,omitempty"`
	// The maximum number of game servers the spawner can handle.
	MaxGameServers       uint32   `protobuf:"varint,3,opt,name=max_game_servers,json=maxGameServers,proto3" json:"max_game_servers,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckStatusResponse) Reset()         { *m = CheckStatusResponse{} }
func (m *CheckStatusResponse) String() string { return proto.CompactTextString(m) }
func (*CheckStatusResponse) ProtoMessage()    {}
func (*CheckStatusResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028c64f744b4b475, []int{1}
}

func (m *CheckStatusResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckStatusResponse.Unmarshal(m, b)
}
func (m *CheckStatusResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckStatusResponse.Marshal(b, m, deterministic)
}
func (m *CheckStatusResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckStatusResponse.Merge(m, src)
}
func (m *CheckStatusResponse) XXX_Size() int {
	return xxx_messageInfo_CheckStatusResponse.Size(m)
}
func (m *CheckStatusResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckStatusResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckStatusResponse proto.InternalMessageInfo

func (m *CheckStatusResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *CheckStatusResponse) GetRunningGameServers() uint32 {
	if m != nil {
		return m.RunningGameServers
	}
	return 0
}

func (m *CheckStatusResponse) GetMaxGameServers() uint32 {
	if m != nil {
		return m.MaxGameServers
	}
	return 0
}

type SpawnServerRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SpawnServerRequest) Reset()         { *m = SpawnServerRequest{} }
func (m *SpawnServerRequest) String() string { return proto.CompactTextString(m) }
func (*SpawnServerRequest) ProtoMessage()    {}
func (*SpawnServerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_028c64f744b4b475, []int{2}
}

func (m *SpawnServerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnServerRequest.Unmarshal(m, b)
}
func (m *SpawnServerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnServerRequest.Marshal(b, m, deterministic)
}
func (m *SpawnServerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnServerRequest.Merge(m, src)
}
func (m *SpawnServerRequest) XXX_Size() int {
	return xxx_messageInfo_SpawnServerRequest.Size(m)
}
func (m *SpawnServerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnServerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnServerRequest proto.InternalMessageInfo

type SpawnServerResponse struct {
	Status Status `protobuf:"varint,1,opt,name=status,proto3,enum=hotel_pb.Status" json:"status,omitempty"`
	// Information about the newly created game server, if successful.
	GameServer           *GameServer `protobuf:"bytes,2,opt,name=game_server,json=gameServer,proto3" json:"game_server,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *SpawnServerResponse) Reset()         { *m = SpawnServerResponse{} }
func (m *SpawnServerResponse) String() string { return proto.CompactTextString(m) }
func (*SpawnServerResponse) ProtoMessage()    {}
func (*SpawnServerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_028c64f744b4b475, []int{3}
}

func (m *SpawnServerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SpawnServerResponse.Unmarshal(m, b)
}
func (m *SpawnServerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SpawnServerResponse.Marshal(b, m, deterministic)
}
func (m *SpawnServerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SpawnServerResponse.Merge(m, src)
}
func (m *SpawnServerResponse) XXX_Size() int {
	return xxx_messageInfo_SpawnServerResponse.Size(m)
}
func (m *SpawnServerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SpawnServerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SpawnServerResponse proto.InternalMessageInfo

func (m *SpawnServerResponse) GetStatus() Status {
	if m != nil {
		return m.Status
	}
	return Status_OK
}

func (m *SpawnServerResponse) GetGameServer() *GameServer {
	if m != nil {
		return m.GameServer
	}
	return nil
}

func init() {
	proto.RegisterType((*CheckStatusRequest)(nil), "hotel_pb.CheckStatusRequest")
	proto.RegisterType((*CheckStatusResponse)(nil), "hotel_pb.CheckStatusResponse")
	proto.RegisterType((*SpawnServerRequest)(nil), "hotel_pb.SpawnServerRequest")
	proto.RegisterType((*SpawnServerResponse)(nil), "hotel_pb.SpawnServerResponse")
}

func init() { proto.RegisterFile("proto/spawner-service.proto", fileDescriptor_028c64f744b4b475) }

var fileDescriptor_028c64f744b4b475 = []byte{
	// 276 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x91, 0x41, 0x4e, 0xc3, 0x30,
	0x14, 0x44, 0x6b, 0x90, 0x2a, 0xf4, 0x2b, 0xa2, 0xca, 0xcd, 0xa2, 0x2a, 0x20, 0x55, 0x59, 0x65,
	0x43, 0x40, 0x41, 0x9c, 0x80, 0x05, 0x1b, 0x56, 0xf1, 0x01, 0x22, 0x37, 0xfa, 0x4a, 0x2b, 0xb0,
	0x1d, 0x6c, 0xa7, 0xf4, 0x2e, 0x5c, 0x81, 0x43, 0xa2, 0xd8, 0x29, 0x71, 0x54, 0x58, 0xb0, 0x4b,
	0x66, 0x46, 0x93, 0xf7, 0x27, 0x70, 0xd5, 0x68, 0x65, 0xd5, 0x9d, 0x69, 0xf8, 0x87, 0x44, 0x7d,
	0x6b, 0x50, 0xef, 0x77, 0x15, 0x66, 0x4e, 0xa5, 0x17, 0x5b, 0x65, 0xf1, 0xad, 0x6c, 0x36, 0x2b,
	0xea, 0x63, 0x95, 0x12, 0x42, 0x49, 0xef, 0x26, 0x31, 0xd0, 0xa7, 0x2d, 0x56, 0xaf, 0xcc, 0x72,
	0xdb, 0x9a, 0x02, 0xdf, 0x5b, 0x34, 0x36, 0xf9, 0x24, 0xb0, 0x18, 0xc9, 0xa6, 0x51, 0xd2, 0x20,
	0x4d, 0x61, 0x6a, 0x9c, 0xb2, 0x24, 0x6b, 0x92, 0x46, 0xf9, 0x3c, 0x3b, 0x96, 0x67, 0x7d, 0xb2,
	0xf7, 0xe9, 0x3d, 0xc4, 0xba, 0x95, 0x72, 0x27, 0xeb, 0xb2, 0xe6, 0x02, 0xcb, 0x8e, 0x09, 0xb5,
	0x59, 0x9e, 0xad, 0x49, 0x7a, 0x59, 0xd0, 0xde, 0x7b, 0xe6, 0x02, 0x99, 0x77, 0x68, 0x0a, 0x73,
	0xc1, 0x0f, 0xe3, 0xf4, 0xb9, 0x4b, 0x47, 0x82, 0x1f, 0x82, 0x64, 0xc7, 0xcc, 0xba, 0x53, 0xfd,
	0xfb, 0x91, 0x79, 0x0f, 0x8b, 0x91, 0xfa, 0x6f, 0xe4, 0x47, 0x98, 0x05, 0x1f, 0x77, 0xa4, 0xb3,
	0x3c, 0x1e, 0xe2, 0x03, 0x42, 0x01, 0xf5, 0xcf, 0x73, 0xfe, 0x45, 0x20, 0x62, 0x7e, 0x79, 0xe6,
	0x87, 0xa7, 0x2f, 0x30, 0x0b, 0xd6, 0xa3, 0xd7, 0x43, 0xc7, 0xe9, 0xd6, 0xab, 0x9b, 0x3f, 0x5c,
	0xcf, 0x9f, 0x4c, 0xba, 0xb6, 0xe0, 0xb0, 0xb0, 0xed, 0x74, 0x85, 0xb0, 0xed, 0x97, 0x35, 0x92,
	0xc9, 0x66, 0xea, 0xfe, 0xfb, 0xc3, 0x77, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbc, 0x72, 0xd2, 0x29,
	0x34, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SpawnerServiceClient is the client API for SpawnerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SpawnerServiceClient interface {
	// Check the current status of the spawner service including asking
	// how many game servers it's currently managing.
	CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error)
	// Request that the service spawn a new game server.
	SpawnServer(ctx context.Context, in *SpawnServerRequest, opts ...grpc.CallOption) (*SpawnServerResponse, error)
}

type spawnerServiceClient struct {
	cc *grpc.ClientConn
}

func NewSpawnerServiceClient(cc *grpc.ClientConn) SpawnerServiceClient {
	return &spawnerServiceClient{cc}
}

func (c *spawnerServiceClient) CheckStatus(ctx context.Context, in *CheckStatusRequest, opts ...grpc.CallOption) (*CheckStatusResponse, error) {
	out := new(CheckStatusResponse)
	err := c.cc.Invoke(ctx, "/hotel_pb.SpawnerService/CheckStatus", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *spawnerServiceClient) SpawnServer(ctx context.Context, in *SpawnServerRequest, opts ...grpc.CallOption) (*SpawnServerResponse, error) {
	out := new(SpawnServerResponse)
	err := c.cc.Invoke(ctx, "/hotel_pb.SpawnerService/SpawnServer", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SpawnerServiceServer is the server API for SpawnerService service.
type SpawnerServiceServer interface {
	// Check the current status of the spawner service including asking
	// how many game servers it's currently managing.
	CheckStatus(context.Context, *CheckStatusRequest) (*CheckStatusResponse, error)
	// Request that the service spawn a new game server.
	SpawnServer(context.Context, *SpawnServerRequest) (*SpawnServerResponse, error)
}

// UnimplementedSpawnerServiceServer can be embedded to have forward compatible implementations.
type UnimplementedSpawnerServiceServer struct {
}

func (*UnimplementedSpawnerServiceServer) CheckStatus(ctx context.Context, req *CheckStatusRequest) (*CheckStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CheckStatus not implemented")
}
func (*UnimplementedSpawnerServiceServer) SpawnServer(ctx context.Context, req *SpawnServerRequest) (*SpawnServerResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SpawnServer not implemented")
}

func RegisterSpawnerServiceServer(s *grpc.Server, srv SpawnerServiceServer) {
	s.RegisterService(&_SpawnerService_serviceDesc, srv)
}

func _SpawnerService_CheckStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnerServiceServer).CheckStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hotel_pb.SpawnerService/CheckStatus",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnerServiceServer).CheckStatus(ctx, req.(*CheckStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SpawnerService_SpawnServer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SpawnServerRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SpawnerServiceServer).SpawnServer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hotel_pb.SpawnerService/SpawnServer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SpawnerServiceServer).SpawnServer(ctx, req.(*SpawnServerRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _SpawnerService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hotel_pb.SpawnerService",
	HandlerType: (*SpawnerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CheckStatus",
			Handler:    _SpawnerService_CheckStatus_Handler,
		},
		{
			MethodName: "SpawnServer",
			Handler:    _SpawnerService_SpawnServer_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/spawner-service.proto",
}
